spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.datasource.url=jdbc:postgresql://localhost:5433/blueprints
spring.datasource.username=blueprints
spring.datasource.password=blueprints
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always